IssuePage/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

aboutme/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
	url(r'^result_table', message_table, name='result_table'),
]

aboutus/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

commentIssue/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import aboutus.urls as aboutus
import IssuePage.urls as IssuePage
import totalIssue.urls as totalIssue
import aboutme.urls as aboutme
import commentIssue.urls as commentIssue
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^aboutus/', include(aboutus, namespace='aboutus')),
    url(r'^IssuePage/', include(IssuePage, namespace='IssuePage')),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),
    url(r'^totalIssue/', include(totalIssue, namespace='totalIssue')),
    url(r'^commentIssue/', include(commentIssue, namespace='commentIssue')),

    url(r'^$', RedirectView.as_view(url= '/dashboard/', permanent='true'), name='redirect_landing_page')
]

totalIssue/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

IssuePage/models.py
from django.db import models

# Create your models here.

aboutme/models.py
from django.db import models
from datetime import date
from django.utils import timezone

DATE_INPUT_FORMATS = ('%d-%m-%Y')


# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=30)
    birthdate = models.DateField(default=date.today)
    gender = models.CharField(max_length=6)
    description = models.CharField(max_length=100)
    email = models.EmailField()

class Expertise(models.Model):
    expertise = models.CharField(max_length=255)

class PhotoURL(models.Model):
    model_pic = models.CharField(max_length=255)

# Create your models here.
class Message(models.Model):
    def convertTimezone():
        return timezone.now() + timezone.timedelta(hours=7)


    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(default=convertTimezone)

    def __str__(self):
        return self.message

aboutus/models.py
from django.db import models

# Create your models here.

commentIssue/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

totalIssue/models.py
from django.db import models

# Create your models here.

aboutme/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

IssuePage/views.py
from django.shortcuts import render

# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'IssuePage/IssuePage.html'
    return render(request, html, response)

aboutme/views.py
from django.shortcuts import render
from .models import Person, Expertise, PhotoURL, Message
from .forms import Message_Form

# Create your views here.


response = {} 
def index(request):
    html = 'aboutme/aboutme.html'
    person = Person.objects.create(name="Kezia Irene", birthdate="1998-10-15", gender="Female", description="A person who always tries to be a better one", email="irenekezia98@.com")
    expertise = Expertise.objects.create(expertise ="Java and Python")
    expertise = Expertise.objects.create(expertise ="Making Fun Music")
    expertise = Expertise.objects.create(expertise ="Business IT Plan")
    model_pic = expertise = PhotoURL.objects.create(model_pic ="https://0.academia-photos.com/22671060/6165818/6987836/s200_kezia_irene.tesiman.jpg_oh_6c416e6db6c808e5087a71965d1a881a_oe_54ffe395___gda___1426160583_a83ba5be6321a5da3e15978004b85cb7")

    
    response['author']= "Kezia Irene"
    response['name'] = Person.objects.all()[0].name
    response['birthdate'] = Person.objects.all()[0].birthdate
    response['gender'] = Person.objects.all()[0].gender
    response['expertise'] = Expertise.objects.all()[0:3]
    response['description'] = Person.objects.all()[0].description
    response['email'] = Person.objects.all()[0].email
    response['model_pic'] = PhotoURL.objects.all()[0].model_pic

    response['message_form'] = Message_Form
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
                          message=response['message'])
        message.save()
        html ='aboutme/form_result.html'
        return render(request, html, response)
    else:        
        return HttpResponseRedirect('/aboutme/')

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'aboutme/table.html'
    return render(request, html,response)

aboutus/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'aboutus/aboutus.html'
    return render(request, html, response)

commentIssue/views.py
from django.shortcuts import render

# Create your views here.

# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'commentIssue/commentIssue.html'
    return render(request, html, response)

dashboard/views.py
from django.shortcuts import render

# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'dashboard/dashboard.html'
    return render(request, html, response)

post/views.py
from django.shortcuts import render

# Create your views here.

totalIssue/views.py
from django.shortcuts import render

# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'totalIssue/totalIssue.html'
    return render(request, html, response)

IssuePage/templates/IssuePage/IssuePage.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Issue Page</title>
<!-- For-Mobile-Apps -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Issue Page" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<script src="{% static 'js/IssuePage.js' %}"></script>
<!-- //For-Mobile-Apps -->
<!-- Style --> <link rel="stylesheet" href="../../static/css/IssuePage.css" type="text/css" media="all" />

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">
                  <img alt="Brand" src="https://lh3.googleusercontent.com/SYz8CSOaKeFhxh0Ul-wgnNFVmr4Tyq-L3QVTyXSWcqV7S-9zqew4z1PqQmIzNk8Zaqg=w300" height="30" width="30">
                </a>
            </div>
            <p class="navbar-text pull-right" id="demo"> </p>
            <!--/.nav-collapse -->
          </div>
          <!--/.container-fluid -->
        </nav>
      </div>
      <br><br><br><br>
    <div id="wrapper" class="container">
        <h1>Lapor Issue</h1>
        <figure class="page-head-image">
          <img src="https://c1.staticflickr.com/3/2622/3796581808_4809b460fc.jpg" />
        </figure>

          <form id="form-work" class="" name="form-work" action="#">
        
        <fieldset>
        
          <div class="text">
          <div class="form-group">
            <div class="col-md-6">
              <label class="control-label" for="issue">Issue</label>
              <input name="nome" class="form-control" placeholder="Broken floor" type="text">
              </div>
            </div>
          </div>
        
         
        <div class="text" style="display:none">
            <div class="form-group">
              <div class="col-md-6">
                <label class="control-label" for="location" >Location</label>
                <input name="surname" class="form-control" placeholder="2nd Floor" type="text">
              </div>
            </div>
        </div>
        
        <div class="text" style="display:none">
            <div class="form-group">
              <div class="col-md-6">
                <label class="control-label" for="discussion" >Discussion</label>
                <input name="surname" class="form-control" placeholder="Berbahaya" type="text">
              </div>
            </div>
        </div>
          
        </fieldset>
        </form>
        <button type="button" class="btn btn-primary btn-lg btn-block info" id="slider1next" >Next</button>
      </div>
      <script>
          var d = new Date();
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          var months = ["January", "February", "March", "April", "May", "June", "July", "Agugust", "September","October","November","December"];
          document.getElementById("demo").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
      </script>
      <script src="{% static 'js/IssuePage.js' %}"></script>
</body>
</html>

aboutme/templates/aboutme/aboutme.html
{% extends "YPM/layout/base.html" %}
{% load staticfiles%}

{% block style %}
    <!-- bootstrap csss -->
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutme.css' %}">
{% endblock %}

{% block content %}
<div class="profile">
<h1>Profile</h1>
</div>
<hr>

<section name="name">
    <p align = "center">
         <img src={{model_pic}} class="img-circle" widht="200" height="200">
    </p>

    <p align = "center">
        <div class = "name">
        <h2 align="center">{{name}}</h2>
        </div>
    </p>
</section>
<hr/>
<section name="about_me">
    <table class="table" align="center">
        <tr>
            <td>Birthday</td>
            <td>{{birthdate}}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr>
            <td>Expertise</td>
            <td>
                {% for data in expertise %}
                    <span class="badge badge-pill badge-primary" id="bege">{{data.expertise}}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{description}}</td>
        </tr>
    </table>
</section>

<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'aboutme:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>



{% endblock %}

aboutme/templates/aboutme/form_result.html
{% extends "YPM/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<h1 style="text-align:center;">Thank you for your message :)</h1>
<br> <h3 style="text-align:center;">Your message will not be visible for others</h3>
<br>
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
{% endblock %}

aboutme/templates/aboutme/table.html
{% extends "YPM/layout/base.html" %}

{% block title %} Kumpulan Pesan {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date.time}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

aboutus/templates/aboutus/aboutus.html
<!DOCTYPE html>
<html>
<head>
<title>Select menu</title>
<!-- For-Mobile-Apps -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Login form" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //For-Mobile-Apps -->
<!-- Style --> <link rel="stylesheet" href="../../static/css/aboutus.css" type="text/css" media="all" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
                  <img alt="Brand" src="https://lh3.googleusercontent.com/SYz8CSOaKeFhxh0Ul-wgnNFVmr4Tyq-L3QVTyXSWcqV7S-9zqew4z1PqQmIzNk8Zaqg=w300" height="30" width="30">
            </div>
            <p class="navbar-text pull-right" id="demo"> </p>
            <!--/.nav-collapse -->
          </div>
          <!--/.container-fluid -->
        </nav>
      </div>
    <br>
     <table class="table" id= "myTable" align="center" cellspacing="40">
            <tr>
                <td>Hi!         :</td>
                <td>Victor</td>
            </tr>
            <tr>
                <td>Sites       :</td>
                <td>PT AW GANCIT</td>
            </tr>
     </table>

     <br>
     <ul class="social-icons">
            <li class="icon icon--facebook">
              <a href="#">
                <span class="icon__name">Lapor Isu</span>
              </a>
            </li>
            <h3>Lapor Isu</h3>
            <br><br><br><br><br><br><br><br><br>
            <li class="icon icon--twitter">
              <a href="#">
                <span class="icon__name">Lihat Isu</span>
              </a>
            </li>
            <h3>Lihat Isu</h3>
    </ul>
                  
</div>


<script>
        var d = new Date();
        var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
        var months = ["January", "February", "March", "April", "May", "June", "July", "Agugust", "September","October","November","December"];
        document.getElementById("demo").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
</script>
</body>
</html>

commentIssue/templates/commentIssue/commentIssue.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Issue Page</title>
<!-- For-Mobile-Apps -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Issue Page" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<!-- //For-Mobile-Apps -->
<!-- Style --> <link rel="stylesheet" href="../../static/css/commentIssue.css" type="text/css" media="all" />

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">
                  <img alt="Brand" src="https://lh3.googleusercontent.com/SYz8CSOaKeFhxh0Ul-wgnNFVmr4Tyq-L3QVTyXSWcqV7S-9zqew4z1PqQmIzNk8Zaqg=w300" height="30" width="30">
                </a>
            </div>
            <p class="navbar-text pull-right" id="demo"> </p>
            <!--/.nav-collapse -->
          </div>
          <!--/.container-fluid -->
        </nav>
      </div>
<br><br>
<header>
        <h2 style="color:rgb(0, 0, 0)">Total Outstanding Issue</h2>
    </header>

    
        <div id="form"  class="container">
              <h3>Comments</h3>
              <div class="comment">
                    <textarea class="textinput" placeholder="Comment"></textarea>
                </div>
              <br>
              <input id="submit" type="submit"  class="btn btn-primary" value="Submit">
              <br>
        </div>
    </div>


    <footer class="footer-basic-centered">

			<p class="footer-company-motto">Pakuwon Smart Reporting Tool</p>


		</footer>
    <script>
            var d = new Date();
            var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
            var months = ["January", "February", "March", "April", "May", "June", "July", "Agugust", "September","October","November","December"];
            document.getElementById("demo").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
            document.getElementById("demo1").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
        </script>

</body>
</html>

dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html>
<head>
<title>Login user interface</title>
<!-- For-Mobile-Apps -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Login form" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //For-Mobile-Apps -->
<!-- Style --> <link rel="stylesheet" href="../../static/css/dashboard.css" type="text/css" media="all" />
</head>
<body>
<div class="container">

<img src="http://semenindonesiabeton.com/wp-content/uploads/2016/03/pakuwon.png" alt="logo pakuwon" height="188" width="375">
	<div class="signin">
     	<form>
	      	<input type="text" class="user" value="Victor" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Victor';}" />
              <input type="password" class="pass" value="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}" />
              <div class="form-group">
                    <label for="sel1">Select Shift:</label>
                    <select class="form-control" id="sel1">
                      <option>Malam, 23.00- 07.00 WIB</option>
                      <option>Pagi</option>
                      <option>Siang</option>
                      <option>Sore</option>
                    </select>
                </div>
	      	<label>
		  		<input type="checkbox" value="Remember-Me" /> Save Password
		  	</label>
          	<input type="submit" value="LOGIN" />
	 	</form>
	</div>
</div>
<div class="footer">
        <p>Pakuwon Smart Reporting Tool</p>
</div>
</body>
</html>

templates/quantum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="perusahaan lowongan">
   <meta name="author" content="{{author}}">
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
   {% block style %}
   {% endblock %}
   <title>
      {% block title %}
      {% endblock %}
   </title>
</head>
<body style="background-image: url(https://www.planwallpaper.com/static/images/518164-backgrounds.jpg)">
   <header>
        {% include "quantum/partials/header.html" %}
   </header>
   <content>
           {% block content %}
           {% endblock %}
   </content>
   <footer class = "footer">
       {% include "quantum/partials/footer.html" %}
   </footer>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

templates/quantum/partials/footer.html
{% load staticfiles %} {% load static %}
<div class="footer">
    <p>Made by &copy; Kezia Irene</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</script>

templates/quantum/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %} {% load static %}

<nav class="navbar navbar-default navbar-static-top">
      <div class="containers">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'aboutus:index' %}">About Us</a></li>
            <li><a href="{% url 'aboutme:index' %}">About Me</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

totalIssue/templates/totalIssue/totalIssue.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Issue Page</title>
<!-- For-Mobile-Apps -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Issue Page" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<!-- //For-Mobile-Apps -->
<!-- Style --> <link rel="stylesheet" href="../../static/css/totalIssue.css" type="text/css" media="all" />

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">
                  <img alt="Brand" src="https://lh3.googleusercontent.com/SYz8CSOaKeFhxh0Ul-wgnNFVmr4Tyq-L3QVTyXSWcqV7S-9zqew4z1PqQmIzNk8Zaqg=w300" height="30" width="30">
                </a>
            </div>
            <p class="navbar-text pull-right" id="demo"> </p>
            <!--/.nav-collapse -->
          </div>
          <!--/.container-fluid -->
        </nav>
      </div>
<br><br>
      <div class="wrapper">

            <header>
                <h1>Total Outstanding Issue</h1>
            </header>
                
        <section class="columns">
            
            <div class="column">
                    <figure class="page-head-image">
                            <img src="https://c1.staticflickr.com/3/2622/3796581808_4809b460fc.jpg" />
                 </figure>
            </div>
            
            <div class="column">
                <h3>Location</h3>
                <p>Broken floor</p>
                <h3>Discussion</h3>
                <p>Berbahaya</p>
                <h3>Issue Date</h3>
                <p id="demo1"></p>
            </div>
          
          <div class="column">
                <h3>Comments</h3>
                <p>Illo quod nemo ratione itaque dolores laudantium error vero laborum blanditiis nostrum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi ratione architecto cum praesentium voluptatibus recusandae?</p>
            </div>
          
          
            
        </section>	
            
        
        
        </div>

        <script>
                var d = new Date();
                var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
                var months = ["January", "February", "March", "April", "May", "June", "July", "Agugust", "September","October","November","December"];
                document.getElementById("demo").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
                document.getElementById("demo1").innerHTML = days[d.getDay()]+", "+ d.getUTCDate() + "-" + months[d.getUTCMonth()] + "-" +d.getUTCFullYear();
            </script>

      </body>
      </html>